---
before_script:
    - "sleep 15"
    - "mongo use recipe_manager"
    - "mongo db.createCollection('planner');"
    - "mongo db.createCollection('recipes');"
install: "npm install"
language: node_js
node_js: "8.16.2"
script: "npm test"
services: mongodb