version: "3"
services:
  app:
    container_name: home-dashboard-recipe-manager
    restart: always
    build: ./
    ports:
      - "80:3001"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: home-dashboard-recipe-manager-mongo-database
    image: mongo
    ports:
      - "27017:27017"