service: home-dashboard-recipe-manager

frameworkVersion: '3'

useDotenv: true

provider:
  lambdaHashingVersion: 20201221
  name: aws
  region: eu-west-1
  runtime: nodejs16.x
  stage: dev
  timeout: 30

functions:
  get-all-planners:
    name: home-dashboard-recipe-manager-get-all-planners
    description: Get all the planners for the recipe manager
    handler: dist/src/api/planner/all.handler
    logRetentionInDays: 7
    environment:
      FIREBASE: ${env:FIREBASE}
    events:
      - http:
          method: get
          path: /api/planner/all
          cors: true
  get-plan-for-day:
    name: home-dashboard-recipe-manager-get-plan-for-day
    description: Gets the plan for a specified day for a planner
    handler: dist/src/api/planner/day.handler
    logRetentionInDays: 7
    environment:
      FIREBASE: ${env:FIREBASE}
    events:
      - http:
          method: get
          path: /api/planner/day
          cors: true